name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer

      - name: Set up Buildozer
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-8-jdk \
            git \
            zip \
            unzip \
            python3-pip \
            python3-setuptools \
            python3-venv \
            libgl1-mesa-dev \
            libgl1-mesa-glx \
            libglu1-mesa

      - name: Build APK
        run: |
          cd your_kivy_app_directory  # Change this to your app directory
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-kivy-app.apk
          path: your_kivy_app_directory/bin/*.apk  # Adjust as needed
